name: ahachatai
services:
  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-ahachatai}
      - POSTGRES_USER=${POSTGRES_USER:-ahachatai}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-nr541Kv59xB4f48bhZOy5wBz}
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ahachat.ai
      - PGADMIN_DEFAULT_PASSWORD=nr541Kv59xB4f48bhZOy5wBz
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ahachatai
      MINIO_ROOT_PASSWORD: nr541Kv59xB4f48bhZOy5wBz
    volumes:
      - s3_data:/data
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 ahachatai nr541Kv59xB4f48bhZOy5wBz;
      /usr/bin/mc mb minio/ahachatai;
      /usr/bin/mc anonymous set public minio/ahachatai/public;
      exit 0;
      "
  redis:
    image: redis:6.2-alpine
    volumes:
        - redis_data:/data
    ports:
        - "6379:6379"
volumes:
  db_data:
  s3_data:
  redis_data:
