packages:
  - apps/*
  - packages/*
  - integrations/*
  - enterprise/apps/*
  - enterprise/packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - core-js-pure
  - esbuild
  - lefthook
  - prisma
