[unix_http_server]
file=/run/supervisord.sock

[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisord.sock

[program:chat]
process_name=%(program_name)s
directory=/app/apps/worker
command=node dist/chat/worker.mjs
autostart=true
autorestart=true
# numprocs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=300

[program:integration]
process_name=%(program_name)s
directory=/app/apps/worker
command=node dist/integration/worker.mjs
autostart=true
autorestart=true
# numprocs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=300

[program:ai-agent]
process_name=%(program_name)s
directory=/app/apps/worker
command=node dist/ai-agent/worker.mjs
autostart=true
autorestart=true
# numprocs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=300

[program:default]
process_name=%(program_name)s
directory=/app/apps/worker
command=node dist/default/worker.mjs
autostart=true
autorestart=true
# numprocs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=300

[program:webhook]
process_name=%(program_name)s
directory=/app/apps/worker
command=node dist/webhook/worker.mjs
autostart=true
autorestart=true
# numprocs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=300

[program:trigger]
process_name=%(program_name)s
directory=/app/apps/worker
command=node dist/trigger/worker.mjs
autostart=true
autorestart=true
# numprocs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=300

[program:analytics]
process_name=%(program_name)s
directory=/app/apps/worker
command=node dist/analytics/worker.mjs
autostart=true
autorestart=true
# numprocs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=300

[program:sequence-scheduler]
process_name=%(program_name)s
directory=/app/apps/worker
command=node dist/sequence-scheduler/worker.mjs
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=300

[program:sequence-producer]
process_name=%(program_name)s
directory=/app/apps/worker
command=node dist/sequence-scheduler/worker-producer.mjs
autostart=true
autorestart=true
# numprocs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=300

[program:sequence-consumer]
process_name=%(program_name)s
directory=/app/apps/worker
command=node dist/sequence-scheduler/worker-consumer.mjs
autostart=true
autorestart=true
# numprocs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=300
