import { customFieldValueChanged } from "./custom-field-value-changed"
import { dateTimeBasedTrigger } from "./date-time-based-trigger"
import {
  archived,
  contactReferredANewContact,
  contactReferredExistingContact,
  contactUnsubscribedFormBroadcast,
  conversationAssigned,
  conversationTransferredToBot,
  conversationTransferredToHuman,
  conversationUnassigned,
  followUp,
  instagramCommentCreated,
  instagramHandoverReceived,
  instagramLiveCommentCreated,
  instagramMentionCreated,
  instagramMessageReceived,
  instagramMessageSeen,
  instagramOptinReceived,
  instagramPostbackReceived,
  instagramReactionReceived,
  instagramReferralReceived,
  instagramStandbyReceived,
  instagramStoryInsights,
  newContact,
  subscribedToSequence,
  unsubscribedFromSequence,
} from "./simple-conditions"
import { tagApplied } from "./tag-applied"
import { tagRemoved } from "./tag-removed"

export const allConditions = {
  tagApplied,
  tagRemoved,
  customFieldValueChanged,
  dateTimeBasedTrigger,
  conversationTransferredToHuman,
  conversationTransferredToBot,
  newContact,
  contactUnsubscribedFormBroadcast,
  archived,
  followUp,
  conversationAssigned,
  conversationUnassigned,
  instagramCommentCreated,
  instagramMessageReceived,
  instagramPostbackReceived,
  instagramReferralReceived,
  instagramOptinReceived,
  instagramMessageSeen,
  instagramMentionCreated,
  instagramLiveCommentCreated,
  instagramReactionReceived,
  instagramHandoverReceived,
  instagramStandbyReceived,
  instagramStoryInsights,
  subscribedToSequence,
  unsubscribedFromSequence,
  contactReferredANewContact,
  contactReferredExistingContact,
}
